// src/Loupe.Angular.Demo.V10/ClientApp/src/app/counter/counter.component.ts
import { Component } from '@angular/core';
import { LoupeService } from "@gibraltarsoftware/loupe-angular";
import { MethodSourceInfo } from "@gibraltarsoftware/loupe-typescript";

@Component({
  selector: 'app-counter-component',
  templateUrl: './counter.component.html'
})
export class CounterComponent {
  public currentCount = 0;

  constructor(
    private readonly loupe: LoupeService
  ) { }

  public incrementCounter() {
    this.currentCount++;

    const someObject = { name: "test", code: 123 };
    this.loupe.information(
      "Angular", "Incrementing Counter", 'Counter is now {0}',
      [this.currentCount], null, JSON.stringify(someObject),
      new MethodSourceInfo("counter.component.ts", "incrementCounter", 23)
    );
  }

}

// src/Loupe.React.Demo/ClientApp/src/components/Counter.js
import React, { Component } from 'react';
import { LoupeAgent } from '@gibraltarsoftware/loupe-typescript';

export class Counter extends Component {
    static displayName = Counter.name;

    constructor(props) {
        super(props);
        this.state = { currentCount: 0 };
        this.incrementCounter = this.incrementCounter.bind(this);
    }

    incrementCounter() {
        this.setState({
            currentCount: this.state.currentCount + 1
        });

        const loupe = new LoupeAgent(window, document);
        loupe.setSessionId('bf8d4505-8b55-4126-afbb-cfb4cb5689fa');
        const someObject = { name: "test", code: 123, nestedObj: { a: 1 } };
        loupe.information(
            "Angular", "Incrementing Counter", 'Counter is now {0}',
            [this.state.currentCount], null, someObject, null
        );
    }

    render() {

        return (
            <div>
                <h1>Counter</h1>

                <p>This is a simple example of a React component.</p>

                <p aria-live="polite">Current count: <strong>{this.state.currentCount}</strong></p>

                <button className="btn btn-primary" onClick={this.incrementCounter}>Increment</button>
            </div>
        );
    }
}
